name: Upload Compiled Code

on:
  release:
    branches:
      - main  # Update with your branch name
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PlatformIO
        uses: platformio/platformio-action@v3

      - name: Compile code
        run: pio run

      - name: Upload compiled code
        uses: actions/upload-artifact@v2
        with:
          name: compiled-code
          path: path/to/your/compiled/code  # Update with the actual path
